on:
  pull_request:
name: Unit tests

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - check-docs
          - test
          - test-acceptance
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Install dependencies
        run: make setup
      - name: make ${{ matrix.target }}
        run: make ${{ matrix.target }}
        env:
          DBT_CLOUD_ACCOUNT_ID: ${{ secrets.TEST_DBT_CLOUD_ACCOUNT_ID }}
          DBT_CLOUD_TOKEN: ${{ secrets.TEST_DBT_CLOUD_TOKEN }}
